import Head from 'next/head'
import ShowLayout from '../components/layouts/ShowLayout'
import Header1 from '../components/Header/Header1/Header1'
import Header2 from '../components/Header/Header2/Header2'
import Header3 from '../components/Header/Header3/Header3'


export default function Home() {
  return ( <ShowLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       

       
        
        
      </ShowLayout>
  )
}
